platform :ios, "8.0"

pod 'AVOSCloud'               
pod 'AVOSCloudIM'             
pod 'AVOSCloudCrashReporting'
pod 'CYLTableViewPlaceHolder'
pod 'Masonry'
pod 'AFNetworking'
pod 'UITableView+FDTemplateLayoutCell'